export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const OPEN_CART_LIST_DRAWER = 'OPEN_CART_LIST_DRAWER';
export const CLOSE_CART_LIST_DRAWER = 'CLOSE_CART_LIST_DRAWER';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SET_VIEW_PRODUCT_ID = 'SET_VIEW_PRODUCT_ID';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';


export const USER_DETAILS = "USER_DETAILS";
export const HANDLE_USERID = "HANDLE_USERID";
export const HANDLE_PASSWORD = "HANDLE_PASSWORD";
export const HANDLE_LOG_OUT = "HANDLE_LOG_OUT";
export const RECEIVED_USER_DETAILS = "RECEIVED_USER_DETAILS";

// export default actionTypes;